version: "3.6"
services:
  front:
    build: ./front
    environment:
      FRONT_URL: http://back:8080
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '0.0001'
          memory: 50M
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  back:
      build: ./back
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 100M
          reservations:
            cpus: '0.0001'
            memory: 50M
